version: '3.8'

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_NAME: crud_db
      DB_USER: postgres
      DB_PASS: postgres
      JWT_SECRET: supersecret
    ports:
      - "3000:3000"
    command: ["npm", "run", "start"]

  db:
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crud_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
